# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
import numpy as np
import pandas as pd

# Challenge 1 - Iterators, Generators and `yield`. 

In iterator in Python is an object that represents a stream of data. However, iterators contain a countable number of values. We traverse through the iterator and return one value at a time. All iterators support a `next` function that allows us to traverse through the iterator. We can create an iterator using the `iter` function that comes with the base package of Python. Below is an example of an iterator.

In [1]:
# We first define our iterator:

iterator = iter([1,2,3])

# We can now iterate through the object using the next function

print(next(iterator))

1

In [2]:
# We continue to iterate through the iterator.

print(next(iterator))

2

In [3]:
print(next(iterator))

3

In [4]:
# After we have iterated through all elements, we will get a StopIteration Error

print(next(iterator))

StopIteration:

In [6]:
# We can also iterate through an iterator using a for loop like this:
# Note: we cannot go back directly in an iterator once we have traversed through the elements. 
# This is why we are redefining the iterator below

iterator = iter([1,2,3])

for i in iterator:
    print(i)

1
2
3

In the cell below, write a function that takes an iterator and returns the first element in the iterator and returns the first element in the iterator that is divisible by 2. Assume that all iterators contain only numeric data. If we have not found a single element that is divisible by 2, return zero.

In [41]:
ton_iterator = iter([1,2,3])

#def divisible2(iterator):
    # This function takes an iterable and returns the first element that is divisible by 2 and zero otherwise
    # Input: Iterable
    # Output: Integer
    
    # Sample Input: iter([1,2,3])
    # Sample Output: 2
    
    # Your code here:
def divisible2(un_iterator):
    for i in un_iterator:
        if i%2 == 0:
            return i
    return 0

divisible2(ton_iterator)

#for i in iterator:
    #if divisible2(i) == 1:
      #  print(divisible2(i))
   # else:
      #  print(0)

2

### Generators

It is quite difficult to create your own iterator since you would have to implement a `next` function. Generators are functions that enable us to create iterators. The difference between a function and a generator is that instead of using `return`, we use `yield`. For example, below we have a function that returns an iterator containing the numbers 0 through n:

In [10]:
def firstn(n):
     number = 0
     while number < n:
         yield number
         number = number + 1

If we pass 5 to the function, we will see that we have a iterator containing the numbers 0 through 4.

In [12]:
iterator = firstn(5)

for i in iterator:
    print(i)

0
1
2
3
4

In the cell below, create a generator that takes a number and returns an iterator containing all even numbers between 0 and the number you passed to the generator.

In [53]:
#def even_iterator(n):
    # This function produces an iterator containing all even numbers between 0 and n
    # Input: integer
    # Output: iterator
    
    # Sample Input: 5
    # Sample Output: iter([0, 2, 4])
    
    # Your code here:
    
def even_iterator(n):   
    number = 0
    while number < n:
        if number % 2 == 0:
            yield number
        number = number + 1

iterator = even_iterator(5)
for i in iterator:
    print(i)

0
2
4

# Challenge 2 - Applying Functions to DataFrames

In this challenge, we will look at how to transform cells or entire columns at once.

First, let's load a dataset. We will download the famous Iris classification dataset in the cell below.

In [59]:

columns = ['sepal_length', 'sepal_width', 'petal_length','petal_width','iris_type']
iris = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", names=columns)

Let's look at the dataset using the `head` function.

In [60]:
# Your code here:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width    iris_type
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Let's start off by using built-in functions. Try to apply the numpy mean function and describe what happens in the comments of the code.

In [65]:
# Your code here:
iris.mean()

pd.DataFrame(iris.mean())

                     0
sepal_length  5.843333
sepal_width   3.054000
petal_length  3.758667
petal_width   1.198667

Next, we'll apply the standard deviation function in numpy (`np.std`). Describe what happened in the comments.

In [68]:
# Your code here:

iris.std()

pd.DataFrame(iris.std())

                     0
sepal_length  0.828066
sepal_width   0.433594
petal_length  1.764420
petal_width   0.763161

The measurements are in centimeters. Let's convert them all to inches. First, we will create a dataframe that contains only the numeric columns. Assign this new dataframe to `iris_numeric`.

In [76]:
# Your code here:
#inch = 0.3977*centi

iris_numeric = iris._get_numeric_data()
iris_numeric

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
5             5.4          3.9           1.7          0.4
6             4.6          3.4           1.4          0.3
7             5.0          3.4           1.5          0.2
8             4.4          2.9           1.4          0.2
9             4.9          3.1           1.5          0.1
10            5.4          3.7           1.5          0.2
11            4.8          3.4           1.6          0.2
12            4.8          3.0           1.4          0.1
13            4.3          3.0           1.1          0.1
14            5.8          4.0           1.2          0.2
15            5.7          4.4           1.5          0.4
16            5.4          3.9           1.3          0.4
17            5.1          3.5           1.4          0.3
18            5.7          3.8           1.7          0.3
19            5.1          3.8           1.5          0.3
20            5.4          3.4           1.7          0.2
21            5.1          3.7           1.5          0.4
22            4.6          3.6           1.0          0.2
23            5.1          3.3           1.7          0.5
24            4.8          3.4           1.9          0.2
25            5.0          3.0           1.6          0.2
26            5.0          3.4           1.6          0.4
27            5.2          3.5           1.5          0.2
28            5.2          3.4           1.4          0.2
29            4.7          3.2           1.6          0.2
..            ...          ...           ...          ...
120           6.9          3.2           5.7          2.3
121           5.6          2.8           4.9          2.0
122           7.7          2.8           6.7          2.0
123           6.3          2.7           4.9          1.8
124           6.7          3.3           5.7          2.1
125           7.2          3.2           6.0          1.8
126           6.2          2.8           4.8          1.8
127           6.1          3.0           4.9          1.8
128           6.4          2.8           5.6          2.1
129           7.2          3.0           5.8          1.6
130           7.4          2.8           6.1          1.9
131           7.9          3.8           6.4          2.0
132           6.4          2.8           5.6          2.2
133           6.3          2.8           5.1          1.5
134           6.1          2.6           5.6          1.4
135           7.7          3.0           6.1          2.3
136           6.3          3.4           5.6          2.4
137           6.4          3.1           5.5          1.8
138           6.0          3.0           4.8          1.8
139           6.9          3.1           5.4          2.1
140           6.7          3.1           5.6          2.4
141           6.9          3.1           5.1          2.3
142           5.8          2.7           5.1          1.9
143           6.8          3.2           5.9          2.3
144           6.7          3.3           5.7          2.5
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

Next, we will write a function that converts centimeters to inches in the cell below. Recall that 1cm = 0.393701in.

In [97]:
def cm_to_in(x):
    return x*0.3937
    


    # This function takes in a numeric value in centimeters and converts it to inches
    # Input: numeric value
    # Output: float
    
    # Sample Input: 1.0
    # Sample Output: 0.393701
    
    # Your code here:

Now convert all columns in `iris_numeric` to inches in the cell below. We like to think of functional transformations as immutable. Therefore, save the transformed data in a dataframe called `iris_inch`.

In [98]:
# Your code here:
iris_numeric.apply(cm_to_in)

     sepal_length  sepal_width  petal_length  petal_width
0         2.00787      1.37795       0.55118      0.07874
1         1.92913      1.18110       0.55118      0.07874
2         1.85039      1.25984       0.51181      0.07874
3         1.81102      1.22047       0.59055      0.07874
4         1.96850      1.41732       0.55118      0.07874
5         2.12598      1.53543       0.66929      0.15748
6         1.81102      1.33858       0.55118      0.11811
7         1.96850      1.33858       0.59055      0.07874
8         1.73228      1.14173       0.55118      0.07874
9         1.92913      1.22047       0.59055      0.03937
10        2.12598      1.45669       0.59055      0.07874
11        1.88976      1.33858       0.62992      0.07874
12        1.88976      1.18110       0.55118      0.03937
13        1.69291      1.18110       0.43307      0.03937
14        2.28346      1.57480       0.47244      0.07874
15        2.24409      1.73228       0.59055      0.15748
16        2.12598      1.53543       0.51181      0.15748
17        2.00787      1.37795       0.55118      0.11811
18        2.24409      1.49606       0.66929      0.11811
19        2.00787      1.49606       0.59055      0.11811
20        2.12598      1.33858       0.66929      0.07874
21        2.00787      1.45669       0.59055      0.15748
22        1.81102      1.41732       0.39370      0.07874
23        2.00787      1.29921       0.66929      0.19685
24        1.88976      1.33858       0.74803      0.07874
25        1.96850      1.18110       0.62992      0.07874
26        1.96850      1.33858       0.62992      0.15748
27        2.04724      1.37795       0.59055      0.07874
28        2.04724      1.33858       0.55118      0.07874
29        1.85039      1.25984       0.62992      0.07874
..            ...          ...           ...          ...
120       2.71653      1.25984       2.24409      0.90551
121       2.20472      1.10236       1.92913      0.78740
122       3.03149      1.10236       2.63779      0.78740
123       2.48031      1.06299       1.92913      0.70866
124       2.63779      1.29921       2.24409      0.82677
125       2.83464      1.25984       2.36220      0.70866
126       2.44094      1.10236       1.88976      0.70866
127       2.40157      1.18110       1.92913      0.70866
128       2.51968      1.10236       2.20472      0.82677
129       2.83464      1.18110       2.28346      0.62992
130       2.91338      1.10236       2.40157      0.74803
131       3.11023      1.49606       2.51968      0.78740
132       2.51968      1.10236       2.20472      0.86614
133       2.48031      1.10236       2.00787      0.59055
134       2.40157      1.02362       2.20472      0.55118
135       3.03149      1.18110       2.40157      0.90551
136       2.48031      1.33858       2.20472      0.94488
137       2.51968      1.22047       2.16535      0.70866
138       2.36220      1.18110       1.88976      0.70866
139       2.71653      1.22047       2.12598      0.82677
140       2.63779      1.22047       2.20472      0.94488
141       2.71653      1.22047       2.00787      0.90551
142       2.28346      1.06299       2.00787      0.74803
143       2.67716      1.25984       2.32283      0.90551
144       2.63779      1.29921       2.24409      0.98425
145       2.63779      1.18110       2.04724      0.90551
146       2.48031      0.98425       1.96850      0.74803
147       2.55905      1.18110       2.04724      0.78740
148       2.44094      1.33858       2.12598      0.90551
149       2.32283      1.18110       2.00787      0.70866

[150 rows x 4 columns]

We have just found that the original measurements were off by a constant. Define the global constant `error` and set it to 2. Write a function that uses the global constant and adds it to each cell in the dataframe. Apply this function to `iris_numeric` and save the result in `iris_constant`.

In [99]:
# Define constant below:
error = 2

def add_constant(x):
    # This function adds a global constant to our input.
    # Input: numeric value
    # Output: numeric value
    
    # Your code here:
    return x + error

iris_numeric = add_constant(iris_numeric)
print(iris_numeric)

     sepal_length  sepal_width  petal_length  petal_width
0             7.1          5.5           3.4          2.2
1             6.9          5.0           3.4          2.2
2             6.7          5.2           3.3          2.2
3             6.6          5.1           3.5          2.2
4             7.0          5.6           3.4          2.2
5             7.4          5.9           3.7          2.4
6             6.6          5.4           3.4          2.3
7             7.0          5.4           3.5          2.2
8             6.4          4.9           3.4          2.2
9             6.9          5.1           3.5          2.1
10            7.4          5.7           3.5          2.2
11            6.8          5.4           3.6          2.2
12            6.8          5.0           3.4          2.1
13            6.3          5.0           3.1          2.1
14            7.8          6.0           3.2          2.2
15            7.7          6.4           3.5          2.4
16            7.4          5.9           3.3          2.4
17            7.1          5.5           3.4          2.3
18            7.7          5.8           3.7          2.3
19            7.1          5.8           3.5          2.3
20            7.4          5.4           3.7          2.2
21            7.1          5.7           3.5          2.4
22            6.6          5.6           3.0          2.2
23            7.1          5.3           3.7          2.5
24            6.8          5.4           3.9          2.2
25            7.0          5.0           3.6          2.2
26            7.0          5.4           3.6          2.4
27            7.2          5.5           3.5          2.2
28            7.2          5.4           3.4          2.2
29            6.7          5.2           3.6          2.2
..            ...          ...           ...          ...
120           8.9          5.2           7.7          4.3
121           7.6          4.8           6.9          4.0
122           9.7          4.8           8.7          4.0
123           8.3          4.7           6.9          3.8
124           8.7          5.3           7.7          4.1
125           9.2          5.2           8.0          3.8
126           8.2          4.8           6.8          3.8
127           8.1          5.0           6.9          3.8
128           8.4          4.8           7.6          4.1
129           9.2          5.0           7.8          3.6
130           9.4          4.8           8.1          3.9
131           9.9          5.8           8.4          4.0
132           8.4          4.8           7.6          4.2
133           8.3          4.8           7.1          3.5
134           8.1          4.6           7.6          3.4
135           9.7          5.0           8.1          4.3
136           8.3          5.4           7.6          4.4
137           8.4          5.1           7.5          3.8
138           8.0          5.0           6.8          3.8
139           8.9          5.1           7.4          4.1
140           8.7          5.1           7.6          4.4
141           8.9          5.1           7.1          4.3
142           7.8          4.7           7.1          3.9
143           8.8          5.2           7.9          4.3
144           8.7          5.3           7.7          4.5
145           8.7          5.0           7.2          4.3
146           8.3          4.5           7.0          3.9
147           8.5          5.0           7.2          4.0
148           8.2          5.4           7.4          4.3
149           7.9          5.0           7.1          3.8

[150 rows x 4 columns]

# Bonus Challenge - Applying Functions to Columns

Read more about applying functions to either rows or columns [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.apply.html) and write a function that computes the maximum value for each row of `iris_numeric`

In [24]:
# Your code here:

Compute the combined lengths for each row and the combined widths for each row using a function. Assign these values to new columns `total_length` and `total_width`.

In [25]:
# Your code here: