# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [1]:
# import numpy and pandas

import numpy as np
import pandas as pd

# Challenge 1 - Index Functions

In this challenge, we will practice the advanced functions introduced in the lesson. However, before we start, we will load and evaluate our dataset.

In [2]:
# Run this code:

admissions = pd.read_csv('../Admission_Predict.csv')
#to remove trailing spaces at the end of the column names
admissions.columns = admissions.columns.str.rstrip()

Let's evaluate the dataset by looking at the `head` function.

In [3]:
# Your code here:
admissions.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,316,104,3,3.0,3.5,8.00,1,0.72
2,3,322,110,3,3.5,2.5,8.67,1,0.80
3,4,314,103,2,2.0,3.0,8.21,0,0.65
4,5,330,115,5,4.5,3.0,9.34,1,0.90

Before beginning to work with this dataset and evaluating graduate admissions data, we will verify that there is no missing data in the dataset. Do this in the cell below.

In [4]:
# Your code here:

admissions.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

Interestingly, there is a column that uniquely identifies the applicants. This column is the serial number column. Instead of having our own index, we should make this column our index. Do this in the cell below. Keep the column in the dataframe in addition to making it an index.

In [5]:
# Your code here:

admissions.index
admissions.index = admissions['Serial No.']
admissions.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,,
1,1,337,118,4,4.5,4.5,9.65,1,0.92
2,2,316,104,3,3.0,3.5,8.00,1,0.72
3,3,322,110,3,3.5,2.5,8.67,1,0.80
4,4,314,103,2,2.0,3.0,8.21,0,0.65
5,5,330,115,5,4.5,3.0,9.34,1,0.90

Turns out that `GRE Score` and `CGPA` also uniquely identify the data. Show this in the cell below.

In [6]:
# Your code here:

#admissions.set_index('GRE Score','CGPA', inplace=True)
#admissions.head()
#(admissions.GRE Score + admissions.CGPA.map(str)).value_counts()
admissions.drop_duplicates(subset=['GRE Score', 'CGPA'], inplace=True)

admissions.set_index(['GRE Score', 'CGPA'], inplace=True)
admissions.head()

,,Serial No.,TOEFL Score,University Rating,SOP,LOR,Research,Chance of Admit
GRE Score,CGPA,,,,,,,
337,9.65,1,118,4,4.5,4.5,1,0.92
316,8.00,2,104,3,3.0,3.5,1,0.72
322,8.67,3,110,3,3.5,2.5,1,0.80
314,8.21,4,103,2,2.0,3.0,0,0.65
330,9.34,5,115,5,4.5,3.0,1,0.90

Replace the index with an index comprised of two columns - `GRE Score` and `CGPA`. Remove the columns from the dataset as well. Make sure to use `inplace=True`.

Now change the index back to a sequence starting at zero using the `reset_index` function. Make sure to use `inplace=True`.

In [7]:
# Your code here:
admissions.reset_index(inplace=True)
admissions.head()

,GRE Score,CGPA,Serial No.,TOEFL Score,University Rating,SOP,LOR,Research,Chance of Admit
0,337,9.65,1,118,4,4.5,4.5,1,0.92
1,316,8.00,2,104,3,3.0,3.5,1,0.72
2,322,8.67,3,110,3,3.5,2.5,1,0.80
3,314,8.21,4,103,2,2.0,3.0,0,0.65
4,330,9.34,5,115,5,4.5,3.0,1,0.90

# Challenge 2 - Advanced Functions

In this part of the lab, we would like to test complex conditions on the entire dataset at once. Let's start by finding the number of rows where the CGPA is higher than 9 and the student has conducted research.

In [8]:
# Your code here:
admissions.loc[(admissions['CGPA'] >= 9) & (admissions['Research'] >= 1)]

,GRE Score,CGPA,Serial No.,TOEFL Score,University Rating,SOP,LOR,Research,Chance of Admit
0,337,9.65,1,118,4,4.5,4.5,1,0.92
4,330,9.34,5,115,5,4.5,3.0,1,0.90
9,327,9.00,10,111,4,4.0,4.5,1,0.84
10,328,9.10,11,112,4,4.0,4.5,1,0.78
19,328,9.50,20,116,5,5.0,5.0,1,0.94
20,334,9.70,21,119,5,5.0,4.5,1,0.95
21,336,9.80,22,119,5,4.0,3.5,1,0.97
28,338,9.40,29,118,4,3.0,4.5,1,0.91
29,340,9.60,30,114,5,4.0,4.0,1,0.90
30,331,9.80,31,112,5,4.0,5.0,1,0.94
31,320,9.20,32,110,5,5.0,5.0,1,0.88
40,326,9.40,41,113,5,4.5,4.0,1,0.91
41,322,9.10,42,110,5,5.0,4.0,1,0.88
42,329,9.30,43,114,5,4.0,5.0,1,0.86
64,318,9.22,65,109,3,3.5,4.0,1,0.68
65,328,9.16,66,115,4,4.5,4.0,1,0.78
66,332,9.64,67,118,5,5.0,5.0,1,0.94
67,336,9.76,68,112,5,5.0,5.0,1,0.96
68,321,9.45,69,111,5,5.0,5.0,1,0.93
69,314,9.04,70,108,4,4.5,4.0,1,0.84
77,340,9.50,78,120,4,5.0,5.0,1,0.96
78,320,9.22,79,110,5,5.0,4.5,1,0.92
79,322,9.36,80,115,5,4.0,4.5,1,0.92
80,340,9.45,81,115,5,4.5,4.5,1,0.94
93,332,9.24,94,119,4,5.0,4.5,1,0.90
99,326,9.05,100,112,3,3.5,3.0,1,0.74
101,329,9.18,102,111,4,4.5,4.5,1,0.87
102,338,9.46,103,117,4,3.5,4.5,1,0.91
103,331,9.38,104,116,5,5.0,5.0,1,0.93
110,310,9.04,111,106,4,4.5,4.5,1,0.66
...,...,...,...,...,...,...,...,...,...
241,335,9.68,242,115,4,4.5,4.5,1,0.93
246,331,9.34,247,119,4,5.0,4.5,1,0.90
247,327,9.13,248,108,5,5.0,3.5,1,0.87
263,329,9.45,264,113,5,5.0,4.5,1,0.89
268,317,9.11,269,110,3,4.0,4.5,1,0.80
271,340,9.66,272,112,4,5.0,4.5,1,0.94
272,331,9.26,273,116,5,4.0,4.0,1,0.93
273,336,9.19,274,118,5,4.5,4.0,1,0.92
274,324,9.08,275,114,5,5.0,4.5,1,0.89
285,330,9.24,286,114,3,4.5,4.5,1,0.90
293,323,9.10,294,110,3,4.0,3.5,1,0.79
294,325,9.00,295,112,4,4.0,4.0,1,0.80
298,328,9.18,299,108,4,4.5,4.0,1,0.84
299,311,9.00,300,107,4,4.5,4.5,1,0.78
311,326,9.14,312,116,3,3.5,4.0,1,0.81
322,332,9.47,323,118,5,5.0,5.0,1,0.94
346,334,9.54,347,116,4,4.0,3.5,1,0.93
347,338,9.23,348,115,5,4.5,5.0,1,0.91
350,330,9.17,351,114,4,4.5,3.0,1,0.86
356,324,9.22,357,110,3,3.5,3.0,1,0.89
357,336,9.62,358,119,4,4.5,4.0,1,0.95
367,324,9.15,368,110,4,4.5,4.0,1,0.82
369,340,9.74,370,113,4,5.0,5.0,1,0.96
370,335,9.82,371,117,5,5.0,5.0,1,0.96
377,326,9.12,378,112,4,4.0,3.5,1,0.84
379,329,9.23,380,111,4,4.5,4.0,1,0.89
380,324,9.04,381,110,3,3.5,3.5,1,0.82
381,325,9.11,382,107,3,3.0,3.5,1,0.84
382,330,9.45,383,116,4,5.0,4.5,1,0.91
384,333,9.66,385,117,4,5.0,4.0,1,0.95

Now return all the rows where the CGPA is greater than 9 and the SOP score is less than 3.5. Find the mean chance of admit for these applicants.

In [9]:
# Your code here:
admissions.loc[(admissions['CGPA'] >= 9) & (admissions['SOP'] <= 3.5)]

,GRE Score,CGPA,Serial No.,TOEFL Score,University Rating,SOP,LOR,Research,Chance of Admit
28,338,9.40,29,118,4,3.0,4.5,1,0.91
62,327,9.02,63,114,3,3.0,3.0,0,0.61
64,318,9.22,65,109,3,3.5,4.0,1,0.68
99,326,9.05,100,112,3,3.5,3.0,1,0.74
102,338,9.46,103,117,4,3.5,4.5,1,0.91
123,326,9.10,124,112,3,3.5,3.0,1,0.84
132,318,9.12,133,109,1,3.5,3.5,0,0.78
140,326,9.11,141,114,3,3.0,3.0,1,0.83
170,319,9.04,171,110,3,3.5,3.5,0,0.82
217,324,9.01,218,111,4,3.0,3.0,1,0.82
231,325,9.04,232,114,3,3.5,3.0,1,0.76
239,316,9.00,240,99,2,2.5,3.0,0,0.70
311,326,9.14,312,116,3,3.5,4.0,1,0.81
356,324,9.22,357,110,3,3.5,3.0,1,0.89
380,324,9.04,381,110,3,3.5,3.5,1,0.82
381,325,9.11,382,107,3,3.0,3.5,1,0.84

We would like to create a deciding factor column for each student. We standardize several columns and then pick the most important factor from a lookup table. If the standardized value is above 0.8, the student will be accepted.

We will start by creating a standardized column for `CGPA`, `GRE Score` and `LOR`. We will name these columns `CGPA_std`, `GRE_std`, and `LOR_std` respecively.

Recall that standardizing a column is done by subtracting the mean of the column from all observations in the column and then dividing each observation in the column by the column's standard deviation.

In the cell below, write a standardization function (a function that takes a column as input and returns a standardized column as output). Make sure to use the `numpy` versions of mean and standard deviation.

In [10]:
def standardize(col):
    # This function takes a column from a dataframe and returns a standardized column by subtracting the column's mean
    # and dividing by the column's standard deviation.
    
    # Your code here:
    return (col-col.mean())/col.std()
#col-col.mean()/np.std(col)

In [11]:
admissions = admissions.rename(columns = {'GRE Score':'GRE_Score'})

Now create the standardized columns `CGPA_std`, `GRE_std`, and `LOR_std` and add them to the `admissions` dataframe.

In [12]:
# Your code here:
admissions['CGPA_std'] = standardize(admissions.CGPA)
admissions['GRE_std'] = standardize(admissions.GRE_Score)
admissions['LOR_std'] = standardize(admissions.LOR)

admissions

,GRE_Score,CGPA,Serial No.,TOEFL Score,University Rating,SOP,LOR,Research,Chance of Admit,CGPA_std,GRE_std,LOR_std
0,337,9.65,1,118,4,4.5,4.5,1,0.92,1.747900,1.753381,1.191647
1,316,8.00,2,104,3,3.0,3.5,1,0.72,-0.991211,-0.063367,0.076740
2,322,8.67,3,110,3,3.5,2.5,1,0.80,0.121034,0.455704,-1.038166
3,314,8.21,4,103,2,2.0,3.0,0,0.65,-0.642597,-0.236391,-0.480713
4,330,9.34,5,115,5,4.5,3.0,1,0.90,1.233279,1.147798,-0.480713
5,321,8.20,6,109,3,3.0,4.0,1,0.75,-0.659198,0.369192,0.634193
6,308,7.90,7,101,2,3.0,4.0,0,0.68,-1.157218,-0.755462,0.634193
7,302,8.00,8,102,1,2.0,1.5,0,0.50,-0.991211,-1.274533,-2.153072
8,323,8.60,9,108,3,3.5,3.0,0,0.45,0.004829,0.542216,-0.480713
9,327,9.00,10,111,4,4.0,4.5,1,0.84,0.668856,0.888263,1.191647
10,328,9.10,11,112,4,4.0,4.5,1,0.78,0.834863,0.974775,1.191647
11,307,8.00,12,109,3,4.0,3.0,1,0.62,-0.991211,-0.841973,-0.480713
12,311,8.20,13,104,3,3.5,2.0,1,0.61,-0.659198,-0.495926,-1.595619
13,314,8.30,14,105,3,3.5,2.5,0,0.54,-0.493191,-0.236391,-1.038166
14,317,8.70,15,107,3,4.0,3.0,0,0.66,0.170836,0.023145,-0.480713
15,319,8.00,16,106,3,4.0,3.0,1,0.65,-0.991211,0.196168,-0.480713
16,318,8.80,17,110,3,4.0,3.0,0,0.63,0.336843,0.109657,-0.480713
17,303,8.50,18,102,3,3.5,3.0,0,0.62,-0.161177,-1.188021,-0.480713
18,325,8.40,19,114,4,3.0,2.0,0,0.70,-0.327184,0.715239,-1.595619
19,328,9.50,20,116,5,5.0,5.0,1,0.94,1.498890,0.974775,1.749100
20,334,9.70,21,119,5,5.0,4.5,1,0.95,1.830903,1.493846,1.191647
21,336,9.80,22,119,5,4.0,3.5,1,0.97,1.996910,1.666869,0.076740
22,322,8.80,23,109,5,4.5,3.5,0,0.76,0.336843,0.455704,0.076740
23,298,7.50,24,98,2,1.5,2.5,1,0.44,-1.821244,-1.620580,-1.038166
24,295,7.20,25,93,1,2.0,2.0,0,0.46,-2.319265,-1.880115,-1.595619
25,310,7.30,26,99,2,1.5,2.0,0,0.54,-2.153258,-0.582438,-1.595619
26,300,8.10,27,97,2,3.0,3.0,1,0.65,-0.825204,-1.447556,-0.480713
27,327,8.30,28,103,3,4.0,4.0,1,0.74,-0.493191,0.888263,0.634193
28,338,9.40,29,118,4,3.0,4.5,1,0.91,1.332883,1.839893,1.191647
29,340,9.60,30,114,5,4.0,4.0,1,0.90,1.664896,2.012916,0.634193
...,...,...,...,...,...,...,...,...,...,...,...,...
355,310,8.24,356,103,2,2.5,2.5,0,0.72,-0.592795,-0.582438,-1.038166
356,324,9.22,357,110,3,3.5,3.0,1,0.89,1.034071,0.628727,-0.480713
357,336,9.62,358,119,4,4.5,4.0,1,0.95,1.698098,1.666869,0.634193
358,321,8.54,359,109,3,3.0,3.0,1,0.79,-0.094775,0.369192,-0.480713
359,315,7.65,360,105,2,2.0,2.5,0,0.39,-1.572234,-0.149879,-1.038166
360,304,7.66,361,101,2,2.0,2.5,0,0.38,-1.555634,-1.101509,-1.038166
361,297,7.43,362,96,2,2.5,2.0,0,0.34,-1.937449,-1.707092,-1.595619
362,290,7.56,363,100,1,1.5,2.0,0,0.47,-1.721640,-2.312674,-1.595619
363,303,7.65,364,98,1,2.0,2.5,0,0.56,-1.572234,-1.188021,-1.038166
364,311,8.43,365,99,1,2.5,3.0,1,0.71,-0.277382,-0.495926,-0.480713
365,322,8.84,366,104,3,3.5,4.0,1,0.78,0.403245,0.455704,0.634193
366,319,8.67,367,105,3,3.0,3.5,1,0.73,0.121034,0.196168,0.076740
367,324,9.15,368,110,4,4.5,4.0,1,0.82,0.917866,0.628727,0.634193
368,300,8.26,369,100,3,3.0,3.5,0,0.62,-0.559593,-1.447556,0.076740
369,340,9.74,370,113,4,5.0,5.0,1,0.96,1.897306,2.012916,1.749100
370,335,9.82,371,117,5,5.0,5.0,1,0.96,2.030111,1.580357,1.749100
371,302,7.96,372,101,2,2.5,3.5,0,0.46,-1.057614,-1.274533,0.076740
372,307,8.10,373,105,2,2.0,3.5,0,0.53,-0.825204,-0.841973,0.076740
373,296,7.80,374,97,2,1.5,2.0,0,0.49,-1.323224,-1.793603,-1.595619
374,320,8.44,375,108,3,3.5,4.0,1,0.76,-0.260781,0.282680,0.634193
375,314,8.24,376,102,2,2.0,2.5,0,0.64,-0.592795,-0.236391,-1.038166
376,318,8.65,377,106,3,2.0,3.0,0,0.71,0.087833,0.109657,-0.480713
377,326,9.12,378,112,4,4.0,3.5,1,0.84,0.868064,0.801751,0.076740
378,317,8.76,379,104,2,3.0,3.0,0,0.77,0.270440,0.023145,-0.480713
379,329,9.23,380,111,4,4.5,4.0,1,0.89,1.050671,1.061286,0.634193
380,324,9.04,381,110,3,3.5,3.5,1,0.82,0.735259,0.628727,0.076740
381,325,9.11,382,107,3,3.0,3.5,1,0.84,0.851463,0.715239,0.076740
382,330,9.45,383,116,4,5.0,4.5,1,0.91,1.415886,1.147798,1.191647
383,312,8.78,384,103,3,3.5,4.0,0,0.67,0.303641,-0.409414,0.634193
384,333,9.66,385,117,4,5.0,4.0,1,0.95,1.764500,1.407334,0.634193

We will generate the decision choice at random using the code below. Please run the cell.

In [19]:
# Run this code:

from random import choices
std_columns = ['CGPA_std', 'GRE_std', 'LOR_std']

decision_choice = choices(std_columns, k=admissions.shape[0])

Now create the deciding column using the `lookup` function. The lookup column is `decision_choice` found above. Call the column resulting from the lookup function `deciding_column` and add it to the `admissions` dataframe.

In [25]:
# Your code here:
lookup = decision_choice
admissions['deciding_column'] = admissions.lookup(admissions.index, lookup)
admissions['deciding_column'].mean()

0.006960981959992122

Create a column called `decision` in the `admissions` dataframe. Assign 1 to this column if the value of `deciding_column` is greater than 0.8 and 0 otherwise.

In [32]:
# Your code here:
admissions['decision'] = 0

In [34]:
admissions.loc[(admissions['deciding_column'] >= 0.8), 'decision'] = 1

In [36]:
admissions.head()

,GRE_Score,CGPA,Serial No.,TOEFL Score,University Rating,SOP,LOR,Research,Chance of Admit,CGPA_std,GRE_std,LOR_std,deciding_column,decision
0,337,9.65,1,118,4,4.5,4.5,1,0.92,1.747900,1.753381,1.191647,1.191647,1
1,316,8.00,2,104,3,3.0,3.5,1,0.72,-0.991211,-0.063367,0.076740,0.076740,0
2,322,8.67,3,110,3,3.5,2.5,1,0.80,0.121034,0.455704,-1.038166,0.121034,0
3,314,8.21,4,103,2,2.0,3.0,0,0.65,-0.642597,-0.236391,-0.480713,-0.236391,0
4,330,9.34,5,115,5,4.5,3.0,1,0.90,1.233279,1.147798,-0.480713,-0.480713,0

How many applicants will be accepted to the program using the decision column? Compute the result below.

In [37]:
# Your code here:

admissions.decision.value_counts()

0    304
1     81
Name: decision, dtype: int64

# Challenge 3 - Method Chaining

To increase our coding efficiency, let's make a number of changes to our dataframe in one line of code.

In the cell below, remove all non character symbols from the column names, replace all spaces in column names to underscores, and change all upper case characters to lower case. Assign these new column values to `admissions.columns`.

In [38]:
# Your code here:

admissions.columns = admissions.columns.str.replace(' ', '_')
admissions.columns = map(str.lower, admissions.columns)
admissions.head()

,gre_score,cgpa,serial_no.,toefl_score,university_rating,sop,lor,research,chance_of_admit,cgpa_std,gre_std,lor_std,deciding_column,decision
0,337,9.65,1,118,4,4.5,4.5,1,0.92,1.747900,1.753381,1.191647,1.191647,1
1,316,8.00,2,104,3,3.0,3.5,1,0.72,-0.991211,-0.063367,0.076740,0.076740,0
2,322,8.67,3,110,3,3.5,2.5,1,0.80,0.121034,0.455704,-1.038166,0.121034,0
3,314,8.21,4,103,2,2.0,3.0,0,0.65,-0.642597,-0.236391,-0.480713,-0.236391,0
4,330,9.34,5,115,5,4.5,3.0,1,0.90,1.233279,1.147798,-0.480713,-0.480713,0

In the cell below, give all student with a university rating of 4 or higher a 10 point boost on their GRE score and split the column into 4 bins using the `cut` function. Assign this new score to the variable `adjusted_gre`.

In [42]:
# Your code here:
admissions['adjusted_gre'] = admissions['gre_score']
admissions.loc[(admissions['gre_score'] >= 4), 'adjusted_gre'] += 10
admissions.head()

,gre_score,cgpa,serial_no.,toefl_score,university_rating,sop,lor,research,chance_of_admit,cgpa_std,gre_std,lor_std,deciding_column,decision,adjusted_gre
0,337,9.65,1,118,4,4.5,4.5,1,0.92,1.747900,1.753381,1.191647,1.191647,1,347
1,316,8.00,2,104,3,3.0,3.5,1,0.72,-0.991211,-0.063367,0.076740,0.076740,0,326
2,322,8.67,3,110,3,3.5,2.5,1,0.80,0.121034,0.455704,-1.038166,0.121034,0,332
3,314,8.21,4,103,2,2.0,3.0,0,0.65,-0.642597,-0.236391,-0.480713,-0.236391,0,324
4,330,9.34,5,115,5,4.5,3.0,1,0.90,1.233279,1.147798,-0.480713,-0.480713,0,340

In [43]:
admissions['adjusted_gre'] = pd.cut(admissions['adjusted_gre'], 4)

In [44]:
admissions

,gre_score,cgpa,serial_no.,toefl_score,university_rating,sop,lor,research,chance_of_admit,cgpa_std,gre_std,lor_std,deciding_column,decision,adjusted_gre
0,337,9.65,1,118,4,4.5,4.5,1,0.92,1.747900,1.753381,1.191647,1.191647,1,"(337.5, 350.0]"
1,316,8.00,2,104,3,3.0,3.5,1,0.72,-0.991211,-0.063367,0.076740,0.076740,0,"(325.0, 337.5]"
2,322,8.67,3,110,3,3.5,2.5,1,0.80,0.121034,0.455704,-1.038166,0.121034,0,"(325.0, 337.5]"
3,314,8.21,4,103,2,2.0,3.0,0,0.65,-0.642597,-0.236391,-0.480713,-0.236391,0,"(312.5, 325.0]"
4,330,9.34,5,115,5,4.5,3.0,1,0.90,1.233279,1.147798,-0.480713,-0.480713,0,"(337.5, 350.0]"
5,321,8.20,6,109,3,3.0,4.0,1,0.75,-0.659198,0.369192,0.634193,0.634193,0,"(325.0, 337.5]"
6,308,7.90,7,101,2,3.0,4.0,0,0.68,-1.157218,-0.755462,0.634193,0.634193,0,"(312.5, 325.0]"
7,302,8.00,8,102,1,2.0,1.5,0,0.50,-0.991211,-1.274533,-2.153072,-0.991211,0,"(299.95, 312.5]"
8,323,8.60,9,108,3,3.5,3.0,0,0.45,0.004829,0.542216,-0.480713,0.004829,0,"(325.0, 337.5]"
9,327,9.00,10,111,4,4.0,4.5,1,0.84,0.668856,0.888263,1.191647,1.191647,1,"(325.0, 337.5]"
10,328,9.10,11,112,4,4.0,4.5,1,0.78,0.834863,0.974775,1.191647,1.191647,1,"(337.5, 350.0]"
11,307,8.00,12,109,3,4.0,3.0,1,0.62,-0.991211,-0.841973,-0.480713,-0.841973,0,"(312.5, 325.0]"
12,311,8.20,13,104,3,3.5,2.0,1,0.61,-0.659198,-0.495926,-1.595619,-0.495926,0,"(312.5, 325.0]"
13,314,8.30,14,105,3,3.5,2.5,0,0.54,-0.493191,-0.236391,-1.038166,-1.038166,0,"(312.5, 325.0]"
14,317,8.70,15,107,3,4.0,3.0,0,0.66,0.170836,0.023145,-0.480713,0.023145,0,"(325.0, 337.5]"
15,319,8.00,16,106,3,4.0,3.0,1,0.65,-0.991211,0.196168,-0.480713,-0.991211,0,"(325.0, 337.5]"
16,318,8.80,17,110,3,4.0,3.0,0,0.63,0.336843,0.109657,-0.480713,0.336843,0,"(325.0, 337.5]"
17,303,8.50,18,102,3,3.5,3.0,0,0.62,-0.161177,-1.188021,-0.480713,-0.161177,0,"(312.5, 325.0]"
18,325,8.40,19,114,4,3.0,2.0,0,0.70,-0.327184,0.715239,-1.595619,-0.327184,0,"(325.0, 337.5]"
19,328,9.50,20,116,5,5.0,5.0,1,0.94,1.498890,0.974775,1.749100,0.974775,1,"(337.5, 350.0]"
20,334,9.70,21,119,5,5.0,4.5,1,0.95,1.830903,1.493846,1.191647,1.493846,1,"(337.5, 350.0]"
21,336,9.80,22,119,5,4.0,3.5,1,0.97,1.996910,1.666869,0.076740,1.996910,1,"(337.5, 350.0]"
22,322,8.80,23,109,5,4.5,3.5,0,0.76,0.336843,0.455704,0.076740,0.455704,0,"(325.0, 337.5]"
23,298,7.50,24,98,2,1.5,2.5,1,0.44,-1.821244,-1.620580,-1.038166,-1.821244,0,"(299.95, 312.5]"
24,295,7.20,25,93,1,2.0,2.0,0,0.46,-2.319265,-1.880115,-1.595619,-1.595619,0,"(299.95, 312.5]"
25,310,7.30,26,99,2,1.5,2.0,0,0.54,-2.153258,-0.582438,-1.595619,-1.595619,0,"(312.5, 325.0]"
26,300,8.10,27,97,2,3.0,3.0,1,0.65,-0.825204,-1.447556,-0.480713,-1.447556,0,"(299.95, 312.5]"
27,327,8.30,28,103,3,4.0,4.0,1,0.74,-0.493191,0.888263,0.634193,0.888263,1,"(325.0, 337.5]"
28,338,9.40,29,118,4,3.0,4.5,1,0.91,1.332883,1.839893,1.191647,1.191647,1,"(337.5, 350.0]"
29,340,9.60,30,114,5,4.0,4.0,1,0.90,1.664896,2.012916,0.634193,2.012916,1,"(337.5, 350.0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,310,8.24,356,103,2,2.5,2.5,0,0.72,-0.592795,-0.582438,-1.038166,-1.038166,0,"(312.5, 325.0]"
356,324,9.22,357,110,3,3.5,3.0,1,0.89,1.034071,0.628727,-0.480713,0.628727,0,"(325.0, 337.5]"
357,336,9.62,358,119,4,4.5,4.0,1,0.95,1.698098,1.666869,0.634193,1.666869,1,"(337.5, 350.0]"
358,321,8.54,359,109,3,3.0,3.0,1,0.79,-0.094775,0.369192,-0.480713,-0.480713,0,"(325.0, 337.5]"
359,315,7.65,360,105,2,2.0,2.5,0,0.39,-1.572234,-0.149879,-1.038166,-1.572234,0,"(312.5, 325.0]"
360,304,7.66,361,101,2,2.0,2.5,0,0.38,-1.555634,-1.101509,-1.038166,-1.038166,0,"(312.5, 325.0]"
361,297,7.43,362,96,2,2.5,2.0,0,0.34,-1.937449,-1.707092,-1.595619,-1.595619,0,"(299.95, 312.5]"
362,290,7.56,363,100,1,1.5,2.0,0,0.47,-1.721640,-2.312674,-1.595619,-1.721640,0,"(299.95, 312.5]"
363,303,7.65,364,98,1,2.0,2.5,0,0.56,-1.572234,-1.188021,-1.038166,-1.038166,0,"(312.5, 325.0]"
364,311,8.43,365,99,1,2.5,3.0,1,0.71,-0.277382,-0.495926,-0.480713,-0.277382,0,"(312.5, 325.0]"
365,322,8.84,366,104,3,3.5,4.0,1,0.78,0.403245,0.455704,0.634193,0.634193,0,"(325.0, 337.5]"
366,319,8.67,367,105,3,3.0,3.5,1,0.73,0.121034,0.196168,0.076740,0.196168,0,"(325.0, 337.5]"
367,324,9.15,368,110,4,4.5,4.0,1,0.82,0.917866,0.628727,0.634193,0.628727,0,"(325.0, 337.5]"
368,300,8.26,369,100,3,3.0,3.5,0,0.62,-0.559593,-1.447556,0.076740,-1.447556,0,"(299.95, 312.5]"
369,340,9.74,370,113,4,5.0,5.0,1,0.96,1.897306,2.012916,1.749100,1.897306,1,"(337.5, 350.0]"
370,335,9.82,371,117,5,5.0,5.0,1,0.96,2.030111,1.580357,1.749100,1.749100,1,"(337.5, 350.0]"
371,302,7.96,372,101,2,2.5,3.5,0,0.46,-1.057614,-1.274533,0.076740,-1.274533,0,"(299.95, 312.5]"
372,307,8.10,373,105,2,2.0,3.5,0,0.53,-0.825204,-0.841973,0.076740,-0.825204,0,"(312.5, 325.0]"
373,296,7.80,374,97,2,1.5,2.0,0,0.49,-1.323224,-1.793603,-1.595619,-1.323224,0,"(299.95, 312.5]"
374,320,8.44,375,108,3,3.5,4.0,1,0.76,-0.260781,0.282680,0.634193,0.282680,0,"(325.0, 337.5]"
375,314,8.24,376,102,2,2.0,2.5,0,0.64,-0.592795,-0.236391,-1.038166,-1.038166,0,"(312.5, 325.0]"
376,318,8.65,377,106,3,2.0,3.0,0,0.71,0.087833,0.109657,-0.480713,0.087833,0,"(325.0, 337.5]"
377,326,9.12,378,112,4,4.0,3.5,1,0.84,0.868064,0.801751,0.076740,0.801751,1,"(325.0, 337.5]"
378,317,8.76,379,104,2,3.0,3.0,0,0.77,0.270440,0.023145,-0.480713,0.270440,0,"(325.0, 337.5]"
379,329,9.23,380,111,4,4.5,4.0,1,0.89,1.050671,1.061286,0.634193,0.634193,0,"(337.5, 350.0]"
380,324,9.04,381,110,3,3.5,3.5,1,0.82,0.735259,0.628727,0.076740,0.076740,0,"(325.0, 337.5]"
381,325,9.11,382,107,3,3.0,3.5,1,0.84,0.851463,0.715239,0.076740,0.715239,0,"(325.0, 337.5]"
382,330,9.45,383,116,4,5.0,4.5,1,0.91,1.415886,1.147798,1.191647,1.191647,1,"(337.5, 350.0]"
383,312,8.78,384,103,3,3.5,4.0,0,0.67,0.303641,-0.409414,0.634193,0.303641,0,"(312.5, 325.0]"
384,333,9.66,385,117,4,5.0,4.0,1,0.95,1.764500,1.407334,0.634193,0.634193,0,"(337.5, 350.0]"